### ISSUE TITLE
incorrect ReSwift source path in Cartfile 

### ISSUE THREAD

**Issue by ichina** [svdo/ReRxSwift#2]
u need to fix source path for ReSwift 
from 
 `github "ReactiveX/ReSwift" ~> 4.0`
to 
`github "ReSwift/ReSwift"`

**Comment by svdo** [comment]
My reasoning for doing it the way I did: both Carthage and CocoaPods use [semantic versioning](https://semver.org). Specifying version `~> 4.0` means: any version `4.x.x`, in other words: `4.0.0 or higher, but less than 5.0.0`. This is on purpose, because by definition version 5.x.x will have API breaking changes compared to version 4.x.x. So I only want to allow major version 4, otherwise everything may break as soon as ReSwift releases version 5.0.0. Makes sense?

I assume you're making this change because of a problem you're running into. If you can describe the problem, I'll try to help you find a solution.

**Comment by ichina** [comment]
amm, i mean you have wrong vendor name here in ReSwift lib, not `ReactiveX`, but `ReSwift`.
everything is ok with semantic versioning

**Comment by ichina** [comment]
this problem is exercised when trying to install ReRxSwift through Carthage

**Comment by svdo** [comment]
Ah I see now, sorry about that. I want to keep the version number, so I'll just change it myself instead of using your pull request. Thanks for reporting this!

**Comment by ichina** [comment]
👍
