### ISSUE TITLE
Are Optional props supported?

### ISSUE THREAD

**Issue by yanshiyason** [svdo/ReRxSwift#4]
Hi there,

I'm used to working with the `connect` function from `react-redux` so it's really cool to see it implemented in swift.

I am trying to bind optional properties and the code won't compile.

```
let forecastKeyPath = \Props.forecast
connection.subscribe(forecastKeyPath) { [weak self] forecast in
    guard let forecast = forecast,
        let currently = forecast.currently else {
            return
    }

    self?.labelTemperature.text = currently.temperature
}
```

The error I get looks like:

```
Cannot convert value of type 'KeyPath<ViewController.Props, Forecast?>' to expected argument type 'KeyPath<_, [_]>'
```

This is my VC:

```
extension ViewController: Connectable {
    struct Props {
        let forecast: Forecast?
        let coordinate: CLLocationCoordinate2D
    }
    struct Actions {
    }
}
```

And I also made sure `Forecast` is `Equatable`

```
extension Forecast: Equatable {
    static func ==(lhs: Forecast, rhs: Forecast) -> Bool {
        if lhs.currently == nil || rhs.currently == nil {
            return false
        }
        return lhs.currently!.time == rhs.currently!.time
    }
}
```

Any advice would be greatly appreciated.

Cheers,

**Comment by svdo** [comment]
Hi! I upgraded to the latest Xcode with Swift 4.1. Because of that, I had to remove the overloads for optionals. Assuming that you’re on an older version of Xcode, I recommend either upgrading Xcode to the latest, or use the before-last version of ReRxSwift, that one still had the overloads for optionals. 

I’d like to reintroduce Swift 4.0 support for optionals using compiler directives, but I don’t have time for that at the moment.

**Comment by yanshiyason** [comment]
Hi! Thank you so much for you answer!

I took a look at the release notes and I guess this is the part which affects us right?

[Implicitly unwrapped optionals may be used only as a top level type for properties, function parameters, function return values, and variables. Nesting them inside other types is deprecated and results in a warning. This will change to an error in a later version of Swift.](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-DontLinkElementID_1)

I will upgrade to the latest Xcode version, Thank you!

**Comment by svdo** [comment]
No in this case it's because `Optional`s are now `Equatable`. Previously there was an implementation in my code for `Equatable` and for `Optional`. In Swift 4.1 the variant for `Optional` is superfluous and causes a compiler error, because the compiler finds to matching overloads and doesn't know which to choose.

If you run into issue after upgrading, let me know.

**Comment by yanshiyason** [comment]
Ah, I see.. thank you for clarifying!

[this is the commit](https://github.com/svdo/ReRxSwift/commit/1180b711cca9ad693b23ff16d28bfe710e380077) which adapts to 4.1 and above then.

Since I am working on a side project just updated my swift version and things are working again. Thanks again for everything!
