### ISSUE TITLE
look like it doesn't support tvos. Any plans?

### ISSUE THREAD

**Issue by CranberryYam** [svdo/ReRxSwift#7]

**Comment by svdo** [comment]
I didn't add explicit support because I never tested it. It should probably work; I just did a quick check and it seems to compile at least. Using Carthage you probably can just include it as is in your project; using Cocoapods requires a modification of the pod spec. Do you want to test it? In that case you could try it out by cloning this repo, changing the pod spec (removing the line with `platform` should do it) and then (in your own project's Podfile) use a local pod reference:

```ruby
pod 'ReRxSwfift', :path => '../ReRxSwfit'
```

I will probably eventually do this myself, but it will take some time which I don't have at the moment, so you can speed it up by testing it...

**Comment by CranberryYam** [comment]
Thanks for replying. I will try it recently.
